"use strict";
const KEY="fitness-ai-hub-v1";
const defaults={profile:{name:"Alif",calories:2000,protein:120,water:2500,activity:30,targetWeight:70},meals:[],activities:[],body:[],sleep:[],water:[]};
let state=load();
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function load(){try{return {...structuredClone(defaults),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`}
function localInputDate(d=new Date()){const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,16)}
function dayKey(v){const d=new Date(v);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function isToday(v){return dayKey(v)===dayKey(new Date())}
function sum(a,key){return a.reduce((n,x)=>n+(Number(x[key])||0),0)}
function esc(v){const d=document.createElement("div");d.textContent=String(v);return d.innerHTML}
function pct(v,g){return Math.min(100,Math.max(0,(v/g)*100||0))}
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function healthToday(){const meals=state.meals.filter(x=>isToday(x.date)),acts=state.activities.filter(x=>isToday(x.date)),sleep=state.sleep.filter(x=>isToday(x.date)),water=sum(state.water.filter(x=>isToday(x.date)),"amount");return{meals,acts,sleep,water,calories:sum(meals,"calories"),protein:sum(meals,"protein"),activity:sum(acts,"duration")}}
function score(t){const c=Math.min(t.calories/state.profile.calories,1),p=Math.min(t.protein/state.profile.protein,1),w=Math.min(t.water/state.profile.water,1),a=Math.min(t.activity/state.profile.activity,1),s=t.sleep.length?Math.min(sum(t.sleep,"hours")/7.5,1):0;return Math.round((c*.15+p*.25+w*.2+a*.2+s*.2)*100)}
function render(){const t=healthToday(),p=state.profile;$("#todayLabel").textContent=new Intl.DateTimeFormat("en-MY",{weekday:"long",day:"numeric",month:"long"}).format(new Date());
 [["calories",t.calories,p.calories," kcal"],["protein",Math.round(t.protein),p.protein," g"],["water",t.water,p.water," ml"],["activity",t.activity,p.activity," min"]].forEach(([id,v,g,u])=>{$(`#${id}Value`).textContent=`${v}${u}`;$(`#${id}Goal`).textContent=`of ${Number(g).toLocaleString()}${u}`;$(`#${id}Progress`).style.width=`${pct(v,g)}%`});
 $("#healthScore strong").textContent=score(t);renderSummaries(t);renderEntries();renderCoach(t);renderSettings();drawWeightChart()}
function renderSummaries(t){$("#mealSummary").innerHTML=t.meals.length?t.meals.slice(-3).reverse().map(x=>`<div class="summary-row"><div><strong>${esc(x.name)}</strong><small>${new Date(x.date).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</small></div><span>${x.calories} kcal</span></div>`).join(""):"No meals logged today.";$("#activitySummary").innerHTML=t.acts.length?t.acts.slice(-3).reverse().map(x=>`<div class="summary-row"><div><strong>${esc(x.name)}</strong><small>${esc(x.source)}</small></div><span>${x.duration} min</span></div>`).join(""):"No activities logged today."}
function allEntries(){return [...state.meals.map(x=>({...x,type:"Meal",detail:`${x.calories} kcal`})),...state.activities.map(x=>({...x,type:"Activity",detail:`${x.duration} min`})),...state.body.map(x=>({...x,type:"Body",name:`${x.weight} kg`,detail:x.bodyFat?`${x.bodyFat}% fat`:"Measurement"})),...state.sleep.map(x=>({...x,type:"Sleep",name:`${x.hours} hours`,detail:`Quality ${x.quality}/5`})),...state.water.map(x=>({...x,type:"Water",name:`${x.amount} ml`,detail:"Hydration"}))].sort((a,b)=>new Date(b.date)-new Date(a.date))}
function renderEntries(){$("#recentEntries").innerHTML=allEntries().slice(0,12).map(x=>`<div class="entry-row"><div><strong>${esc(x.type)}: ${esc(x.name)}</strong><small>${new Date(x.date).toLocaleString()}</small></div><span>${esc(x.detail)}</span></div>`).join("")||'<div class="empty-state">Nothing logged yet.</div>'}
function renderCoach(t){const s=score(t),name=esc(state.profile.name||"there"),items=[];$("#coachSummary").textContent=s>=80?`Strong day, ${name}. You are meeting most of your daily health targets.`:s>=50?`Good progress, ${name}. A few focused actions can improve today’s score.`:`Start simple, ${name}. Log your meal, drink water and add some movement.`;
 if(t.protein<state.profile.protein*.7)items.push(["warn",`Protein is ${Math.round(t.protein)} g. You need about ${Math.max(0,Math.round(state.profile.protein-t.protein))} g more to reach your target.`]);else items.push(["good","Protein intake is on track today."]);if(t.water<state.profile.water*.7)items.push(["warn",`Hydration is below target. Add ${Math.max(0,state.profile.water-t.water)} ml gradually today.`]);else items.push(["good","Hydration is on track."]);if(t.activity<state.profile.activity)items.push(["warn",`${Math.max(0,state.profile.activity-t.activity)} more active minutes will reach your goal.`]);else items.push(["good","Activity target achieved."]);$("#coachInsights").innerHTML=items.map(x=>`<div class="insight ${x[0]}">${x[1]}</div>`).join("")}
function renderSettings(){const p=state.profile;$("#profileName").value=p.name;$("#goalCalories").value=p.calories;$("#goalProtein").value=p.protein;$("#goalWater").value=p.water;$("#goalActivity").value=p.activity;$("#goalWeight").value=p.targetWeight}
function drawWeightChart(){const c=$("#weightChart"),ctx=c.getContext("2d"),ratio=devicePixelRatio||1,w=c.clientWidth,h=190;c.width=w*ratio;c.height=h*ratio;ctx.scale(ratio,ratio);ctx.clearRect(0,0,w,h);const data=state.body.slice().sort((a,b)=>new Date(a.date)-new Date(b.date)).slice(-7);$("#latestWeight").textContent=data.length?`${data.at(-1).weight} kg`:"No data";ctx.strokeStyle="#253850";ctx.fillStyle="#91a4b9";ctx.font="11px system-ui";for(let i=0;i<4;i++){const y=20+i*45;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}if(!data.length){ctx.fillText("Add body measurements to see your trend.",10,100);return}const vals=data.map(x=>Number(x.weight)),min=Math.min(...vals)-.5,max=Math.max(...vals)+.5,step=data.length===1?0:(w-30)/(data.length-1);ctx.beginPath();data.forEach((x,i)=>{const px=15+i*step,py=165-((x.weight-min)/(max-min))*135;i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.strokeStyle="#5ee6b5";ctx.lineWidth=3;ctx.stroke();data.forEach((x,i)=>{const px=15+i*step,py=165-((x.weight-min)/(max-min))*135;ctx.fillStyle="#5ee6b5";ctx.beginPath();ctx.arc(px,py,4,0,Math.PI*2);ctx.fill();ctx.fillStyle="#eff7ff";ctx.fillText(`${x.weight}`,Math.max(0,px-12),Math.max(12,py-9))})}
function addForm(formId,collection,mapper){$(formId).addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget);state[collection].push({id:uid(),...mapper(f)});save();e.currentTarget.closest("dialog").close();e.currentTarget.reset();toast("Saved successfully")})}
$$('[data-open]').forEach(b=>b.addEventListener("click",()=>{const d=$(`#${b.dataset.open}`);const date=$("[name=date]",d);if(date)date.value=localInputDate();d.showModal()}));$$('[data-close]').forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));$$('dialog').forEach(d=>d.addEventListener("click",e=>{if(e.target===d)d.close()}));
$$('[data-view]').forEach(b=>b.addEventListener("click",()=>{$$('.nav-button').forEach(x=>x.classList.toggle("active",x===b));$$('.view').forEach(x=>x.classList.toggle("active",x.id===b.dataset.view));scrollTo(0,0);if(b.dataset.view==="dashboard")drawWeightChart()}));
addForm("#mealForm","meals",f=>({name:f.get("name"),calories:+f.get("calories"),protein:+f.get("protein"),carbs:+f.get("carbs"),fat:+f.get("fat"),date:f.get("date")}));
addForm("#activityForm","activities",f=>({name:f.get("name"),duration:+f.get("duration"),calories:+f.get("calories"),distance:+f.get("distance"),source:f.get("source"),date:f.get("date")}));
addForm("#bodyForm","body",f=>({weight:+f.get("weight"),bodyFat:+f.get("bodyFat")||null,muscle:+f.get("muscle")||null,bmi:+f.get("bmi")||null,date:f.get("date")}));
addForm("#sleepForm","sleep",f=>({hours:+f.get("hours"),quality:+f.get("quality"),date:f.get("date")}));
$("#addWater").addEventListener("click",()=>{state.water.push({id:uid(),name:"Water",amount:250,date:new Date().toISOString()});save();toast("250 ml water added")});
$("#settingsForm").addEventListener("submit",e=>{e.preventDefault();state.profile={name:$("#profileName").value.trim(),calories:+$("#goalCalories").value,protein:+$("#goalProtein").value,water:+$("#goalWater").value,activity:+$("#goalActivity").value,targetWeight:+$("#goalWeight").value};save();toast("Settings saved")});
$("#clearToday").addEventListener("click",()=>{if(!confirm("Delete all entries logged today?"))return;["meals","activities","body","sleep","water"].forEach(k=>state[k]=state[k].filter(x=>!isToday(x.date)));save();toast("Today cleared")});
$("#exportData").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`fitness-ai-backup-${dayKey(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)});
$("#importData").addEventListener("change",async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!data.profile||!Array.isArray(data.meals))throw Error();state={...structuredClone(defaults),...data};save();toast("Backup imported")}catch{alert("This backup file is not valid.")}e.target.value=""});
$("#resetData").addEventListener("click",()=>{if(confirm("Permanently delete all app data on this device?")){state=structuredClone(defaults);save();toast("App reset")}});
$("#askCoach").addEventListener("click",()=>{const q=$("#coachQuestion").value.toLowerCase().trim(),t=healthToday();let a="Ask me about calories, protein, water, activity, sleep, weight, or today’s progress.";if(q.includes("calor"))a=`You have logged ${t.calories} of ${state.profile.calories} kcal today, leaving ${Math.max(0,state.profile.calories-t.calories)} kcal.`;else if(q.includes("protein"))a=`You have logged ${Math.round(t.protein)} of ${state.profile.protein} g protein, leaving about ${Math.max(0,Math.round(state.profile.protein-t.protein))} g.`;else if(q.includes("water")||q.includes("hydrat"))a=`You have logged ${t.water} ml. Your remaining hydration target is ${Math.max(0,state.profile.water-t.water)} ml.`;else if(q.includes("activity")||q.includes("exercise")||q.includes("workout"))a=`You have ${t.activity} active minutes today. ${Math.max(0,state.profile.activity-t.activity)} minutes remain.`;else if(q.includes("sleep"))a=t.sleep.length?`You logged ${sum(t.sleep,"hours").toFixed(1)} hours of sleep today.`:"No sleep has been logged today.";else if(q.includes("weight")){const b=state.body.slice().sort((x,y)=>new Date(y.date)-new Date(x.date))[0];a=b?`Your latest weight is ${b.weight} kg, and your goal is ${state.profile.targetWeight} kg.`:"Log your first body measurement to begin weight analysis."}else if(q)a=`Your daily health score is ${score(t)}/100. Focus next on the lowest of protein, water, activity, and sleep.`;$("#coachAnswer").textContent=a});
function network(){const off=!navigator.onLine;$("#offlineBanner").hidden=!off}addEventListener("online",network);addEventListener("offline",network);network();
let installPrompt;addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("#installButton").hidden=false});$("#installButton").addEventListener("click",async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("#installButton").hidden=true});
if("serviceWorker" in navigator){addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").then(()=>$("#swStatus").textContent="Ready").catch(()=>$("#swStatus").textContent="Unavailable"))}else $("#swStatus").textContent="Not supported";
addEventListener("resize",()=>drawWeightChart());render();